In [1]:
from image_inspector import ImageInspector

In [2]:
import os

In [3]:
imgs = os.listdir('../input/images/')
path = '../input/images/'

In [4]:
categories = ['Anchor', 'Apple', 'Baby bottle', 'Bomb', 'Cactus','Candle', 'Taxi car', 'Carrot', 'Chess knight', 'Clock', 'Clown','Diasy flower', 'Dinosaur','Dolphin', 'Dragon', 'Exclamation point','Eye', 'Fire', 'Four leaf clover', 'Ghost', 'Green splats', 'Hammer','Heart', 'Ice cube', 'Igloo', 'Key', 'Ladybird (Ladybug)', 'Light bulb','Lightning bolt', 'Lock', 'Maple leaf', 'Moon', 'No Entry sign','Orange scarecrow man', 'Pencil', 'Purple bird', 'Purple cat','Purple dobble hand man', 'Red lips', 'Scissors', 'Skull and crossbones','Snowflake', 'Snowman', 'Spider', 'Spider’s web', 'Sun', 'Sunglasses','Target/crosshairs', 'Tortoise', 'Treble clef', 'Tree', 'Water drip','Dog', 'Yin and Yang', 'Zebra', 'Question mark', 'Cheese']

In [5]:
ii = ImageInspector(imgs, path, categories, n_cols=5)

In [6]:
ii()

AppLayout(children=(GridspecLayout(children=(ToggleButton(value=False, description='Anchor', layout=Layout(gri…

In [39]:
results = ii.get_results()

In [41]:
results.head()

,Anchor,Apple,Baby bottle,Bomb,Cactus,Candle,Taxi car,Carrot,Chess knight,Clock,...,Tortoise,Treble clef,Tree,Water drip,Dog,Yin and Yang,Zebra,Question mark,Cheese,Image Name
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,IMG_20201021_183116_1.jpg
1,False,False,False,False,False,False,False,False,True,False,...,False,True,False,True,False,False,False,False,False,IMG_20201021_183145.jpg
2,False,False,False,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,IMG_20201021_183250_1.jpg
3,True,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,IMG_20201021_183035.jpg
4,False,False,False,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,IMG_20201021_182733.jpg

In [48]:
results[categories] = results[categories].astype(int)
results.head()

,Anchor,Apple,Baby bottle,Bomb,Cactus,Candle,Taxi car,Carrot,Chess knight,Clock,...,Tortoise,Treble clef,Tree,Water drip,Dog,Yin and Yang,Zebra,Question mark,Cheese,Images
0,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,IMG_20201021_183116_1.jpg
1,0,0,0,0,0,0,0,0,1,0,...,0,1,0,1,0,0,0,0,0,IMG_20201021_183145.jpg
2,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,IMG_20201021_183250_1.jpg
3,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,IMG_20201021_183035.jpg
4,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,IMG_20201021_182733.jpg

In [49]:
results.to_pickle('../input/neural_net_df.pkl')

In [86]:
results.loc[index, categories].index[results.loc[index, categories]==1].tolist()

['Taxi car',
 'Clown',
 'Four leaf clover',
 'Maple leaf',
 'Purple bird',
 'Purple cat',
 'Sun',
 'Dog']

In [87]:
cats = []
for index in results.index:
    temp = results.loc[index, categories].index[results.loc[index, categories]==1].tolist()
    cats.append(temp)

In [91]:
data_df = pd.DataFrame({'images': results.Images, 'categories': cats})

In [93]:
data_df.to_pickle('../input/data.pkl')